# Generated by Django 5.2.11 on 2026-02-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('company_summary', models.TextField(blank=True, null=True)),
                ('generated_email', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ENRICHING', 'Enriching'), ('ENRICHED', 'Enriched'), ('EMAIL_SENT', 'Email Sent'), ('FAILED', 'Failed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
