version: '3.9'
services:
  web:
    build: .
    command: gunicorn ai_lead_enrichment.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

  worker:
    build: .
    command: celery -A ai_lead_enrichment worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always
  redis:
    image: redis:7
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ai_leads_db
      MYSQL_ROOT_PASSWORD: "Laptop@123"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart:  always

volumes:
  mysql_data:


