version: "3.9"

services:

  web:
    build: .
    command: gunicorn ai_lead_enrichment.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always

    environment:
      MYSQL_DATABASE: ai_leads_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Strongpassword123
      MYSQL_HOST: ai-lead-db.cjaqiiema1tl.ap-south-1.rds.amazonaws.com
      MYSQL_PORT: 3306

    depends_on:
      - redis

  worker:
    build: .
    command: celery -A ai_lead_enrichment worker -l info
    restart: always

    environment:
      MYSQL_DATABASE: ai_leads_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Strongpassword123
      MYSQL_HOST: ai-lead-db.cjaqiiema1tl.ap-south-1.rds.amazonaws.com
      MYSQL_PORT: 3306

    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

  redis:
    image: redis:7
    restart: always