apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  REDIS_URL: "redis://redis:6379/0"
  MYSQL_DATABASE: "ai_leads_db"
  MYSQL_USER: "root"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"