apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_PASSWORD: "CHANGE_ME"
  GROQ_API_KEY: "CHANGE_ME"
  TAVILY_API_KEY: "CHANGE_ME"
  EMAIL_HOST_USER: "CHANGE_ME"
  EMAIL_HOST_PASSWORD: "CHANGE_ME"

