apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: karthikakutty/ai-leads:latest
        command: ["celery", "-A", "ai_lead_enrichment", "worker", "-l", "info"]
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets